### ISSUE TITLE
Guise.vimのEDITOR proxyがまれに失敗する

### ISSUE THREAD

**Issue by kyoh86** [kyoh86/dotfiles#34]
denoのコネクションが失敗しちゃうケースがあるっぽい？

```console
$ gh pr create --draft
? Where should we push the 'op' branch? example/foo

Creating draft pull request for op into develop in example/foo

? Title refactor: devutilの解体
? Choose a template PULL_REQUEST_TEMPLATE.md
? Body [(e) to launch editor.ts, enter to skip] A new release of Deno is available: 1.34.3 → 1.35.0 Run `deno upgrade` to install it.
error: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
const conn = await Deno.connect(addr);
             ^
    at async Object.connect (ext:deno_net/01_net.js:473:55)
    at async file:///home/kyoh86/.local/share/nvim/lazy/gin.vim/denops/gin/proxy/editor.ts:19:14

X operation failed. To restore: gh pr create --recover /tmp/gh1604740742.json

could not prompt: exit status 1
```

**Comment by kyoh86** [comment]
解消済
