### ISSUE TITLE
ddu-source-gitでちょくちょくエラーが出る

### ISSUE THREAD

**Issue by kyoh86** [kyoh86/dotfiles#5]
```
[denops] (ddu-source-git) Unhandled rejection is detected. Worker will be reloaded: NoMethodFoundError: No MessagePack-RPC method 'redrawCurrentDdu' exists
[denops]     at dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/dispatcher.ts:42:13)
[denops]     at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:244:28)
[denops]     at Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:271:53)
[denops]     at Session.#handleMessage (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:255:37)
[denops]     at Object.write (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:159:63)
[denops]     at Object.invokeCallbackFunction (internal:ext/webidl/00_webidl.js:869:18)
[denops]     at WritableStreamDefaultController.writeAlgorithm (internal:ext/web/06_streams.js:3534:16)
[denops]     at writableStreamDefaultControllerProcessWrite (internal:ext/web/06_streams.js:4045:57)
[denops]     at writableStreamDefaultControllerAdvanceQueueIfNeeded (internal:ext/web/06_streams.js:3948:7)
[denops]     at writableStreamDefaultControllerWrite (internal:ext/web/06_streams.js:4092:5)
```

曰く:  
https://vim-jp.slack.com/archives/C05AM6ET6F8/p1687048444660299?thread_ts=1686897051.317149&cid=C05AM6ET6F8

> ソースコード確認しました。これは source 側の問題です  
> redrawCurrentDdu を自前で定義しているようですが、これの読み込み前に呼び出そうとしています。  
> プラグインの読み込みは非同期になるので、ちゃんと読み込みを確認してから呼び出そうとしないとだめ。

起動が遅延したときに出るのか。なるほど。

**Comment by kyoh86** [comment]
ddu-source-gitちょいちょい直したいところあるのでそれも合わせて直す（また尻が重くなる）

**Comment by kyoh86** [comment]
一旦Issue切ったので閉じる
