### ISSUE TITLE
ddu-source-git_branchのswitchが上手く動かない

### ISSUE THREAD

**Issue by kyoh86** [kyoh86/dotfiles#72]
```
E5108: Error executing lua: function ddu#ui#do_action[1]..ddu#ui#sync_action[1]..ddu#ui_sync_action[4]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request, line 1: Vim(return):Error invoking 'invoke' on channel 5 (denops):
0,function ddu#ui#do_action[1]..ddu#ui#sync_action[1]..ddu#ui_sync_action[4]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request[1]..ddu#item_action[1]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request, line 1: Vim(return):Error invoking 'invoke' on channel 5 (denops):
BatchError: function ddu#ui#do_action[1]..ddu#ui#sync_action[1]..ddu#ui_sync_action[4]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request[1]..ddu#item_action[1]..ddu#denops#_request[15]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request[1]..denops#api#cmd, line 2: Vim(echomsg):E121: Undefined variable: ddu
    at DenopsImpl.batch (file:///home/kyoh86/.local/share/nvim/lazy/denops.vim/denops/@denops-private/impl.ts:62:13)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async batch (https://deno.land/x/denops_std@v5.2.0/batch/batch.ts:199:3)
    at async echomsg (https://denopkg.com/kyoh86/denops-util@v0.0.3/echomsg.ts:5:3)
    at async Object.write (https://denopkg.com/kyoh86/denops-util@v0.0.3/echomsg_stream.ts:10:9)
stack traceback:
	[C]: at 0x55e36f426fd0
"app/candidate-search/components/CandidateSearch.tsx" 94L, 3233B
```

**Comment by Shougo** [comment]
`Undefined variable: ddu`

**Comment by kyoh86** [comment]
yes.

**Comment by Shougo** [comment]
手元で試しましたが、エラー以前にアクション実行するとフリーズしてます。使いものになってないですね

**Comment by kyoh86** [comment]
はい。分かってます。ちょっとほっといてください。僕の問題なので。
